##############################
# Terraform Requirements
##############################
terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "~> 1.49"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

variable "hcloud_token" {
  sensitive = true
}

provider "hcloud" {
  token = var.hcloud_token
}

##############################
# 1) Network & Subnet
##############################
resource "hcloud_network" "vpc" {
  name     = "multiple_jump_network"
  ip_range = "10.0.0.0/16"
}

resource "hcloud_network_subnet" "multiple_jump_network_subnet" {
  network_id   = hcloud_network.vpc.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/24"
}

##############################
# 2) Local SSH Keys (bastion, internal, application)
##############################
# These are generated by Ansible on your local machine, no passphrase
resource "hcloud_ssh_key" "bastion_ssh" {
  name       = "bastion_root_key"
  public_key = file("~/.ssh/bastion_key_temp.pub")
}

resource "hcloud_ssh_key" "internal_ssh" {
  name       = "internal_root_key"
  public_key = file("~/.ssh/internal_key_temp.pub")
}

resource "hcloud_ssh_key" "application_ssh" {
  name       = "application_root_key"
  public_key = file("~/.ssh/application_key_temp.pub")
}

##############################
# 3) Minimal Cloud-Init
##############################
locals {
  server_config_file = "${path.module}/server_config.yaml"
  server_user_data   = file(local.server_config_file)
}

##############################
# 4) Bastion Server
##############################
resource "hcloud_server" "bastion" {
  name        = "bastion-host"
  server_type = "cx22"
  image       = "ubuntu-24.04"
  location    = "fsn1"

  # Inject your root SSH key to Hetzner
  ssh_keys = [
    hcloud_ssh_key.bastion_ssh.name
  ]

  network {
    network_id = hcloud_network.vpc.id
  }

  user_data = local.server_user_data
  
  # (A) Remote-exec: Generate an ECDSA key "id_internal_ecdsa" on the *bastion* server
  provisioner "remote-exec" {
    inline = [
      "ssh-keygen -t ecdsa -N '' -f /root/.ssh/id_internal_ecdsa",
      "cat /root/.ssh/id_internal_ecdsa.pub > /tmp/id_internal_ecdsa_public_key.pub"
    ]
    connection {
      type        = "ssh"
      user        = "root"
      private_key = file("~/.ssh/bastion_key_temp") # The matching private key from your local machine
      host        = self.ipv4_address
    }
  }

  # (B) Local-exec: Copy that pubkey back to local
  provisioner "local-exec" {
    command = <<-EOT
      scp \
        -i ~/.ssh/bastion_key_temp \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        root@${self.ipv4_address}:/tmp/id_internal_ecdsa_public_key.pub \
        ./id_internal_ecdsa_public_key.pub
    EOT
  }
}

##############################
# 5) Data Source: local_file (internal key)
##############################
data "local_file" "internal_public_key_relay" {
  # This file is scp'ed from the bastion's remote-exec step
  filename = "${path.module}/id_internal_ecdsa_public_key.pub"
}

##############################
# 6) Relay Key for the internal server
##############################
resource "hcloud_ssh_key" "internal_ssh_relay" {
  depends_on = [hcloud_server.bastion]

  name       = "internal_ssh_key_from_bastion"
  public_key = data.local_file.internal_public_key_relay.content
}

############################################
# 7) Internal Server (unchanged from your code)
############################################
resource "hcloud_server" "internal" {
  depends_on = [hcloud_server.bastion]
  name       = "internal-relay"
  server_type = "cx22"
  image      = "ubuntu-24.04"
  location   = "fsn1"

  # Use BOTH the local key + the relay key from the bastion
  ssh_keys = [
    hcloud_ssh_key.internal_ssh.name,
    hcloud_ssh_key.internal_ssh_relay.name
  ]

  network {
    network_id = hcloud_network.vpc.id
  }

  user_data = local.server_user_data

  # (A) Remote-exec: Generate "id_application_ecdsa" on the *internal* server
  provisioner "remote-exec" {
    inline = [
      "ssh-keygen -t ecdsa -N '' -f /root/.ssh/id_application_ecdsa",
      "cat /root/.ssh/id_application_ecdsa.pub > /tmp/id_application_ecdsa_public_key.pub"
    ]
    connection {
      type        = "ssh"
      user        = "root"
      private_key = file("~/.ssh/internal_key_temp")
      host        = self.ipv4_address
    }
  }

  # (B) Local-exec: Copy that pubkey back to local
  provisioner "local-exec" {
    command = <<-EOT
      scp \
        -i ~/.ssh/internal_key_temp \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        root@${self.ipv4_address}:/tmp/id_application_ecdsa_public_key.pub \
        ./id_application_ecdsa_public_key.pub
    EOT
  }
}

############################################
# 8) Data Source: local_file (application key)
############################################
data "local_file" "application_public_key_relay" {
  # The file we just scp'ed from the internal server
  filename = "${path.module}/id_application_ecdsa_public_key.pub"
}

############################################
# 9) Relay Key for the application server
############################################
resource "hcloud_ssh_key" "application_ssh_relay" {
  depends_on = [hcloud_server.internal]

  name       = "application_ssh_key_from_internal"
  public_key = data.local_file.application_public_key_relay.content
}

############################################
# 10) Application Server
############################################
resource "hcloud_server" "application" {
  depends_on = [hcloud_server.internal]
  name       = "application-host"
  server_type = "cx22"
  image      = "ubuntu-24.04"
  location   = "fsn1"

  ssh_keys = [
    hcloud_ssh_key.application_ssh.name,
    hcloud_ssh_key.application_ssh_relay.name
  ]

  network {
    network_id = hcloud_network.vpc.id
  }
}

output "bastion_ip" {
  description = "Public IPv4 of the bastion (or private, if you have a direct route)."
  value       = hcloud_server.bastion.ipv4_address
}

output "internal_ip" {
  description = "IP of the internal server."
  value       = hcloud_server.internal.ipv4_address
}

output "application_ip" {
  description = "IP of the application server."
  value       = hcloud_server.application.ipv4_address
}
